{% set name = "pybigquery" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9e9f86ab96eb604633eb92cda5d9f1e8c034369e783fdc8222143bb841e68c8

build:
  noarch: python
  entry_points:
    - bigquery = pybigquery.sqlalchemy_bigquery:BigQueryDialect
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - sqlalchemy >=1.1.9
    - google-cloud-bigquery >=1.6.0
    - future

test:
  imports:
    - pybigquery
    - pybigquery.api
    - pybigquery.parse_url
    - pybigquery.sqlalchemy_bigquery

about:
  home: https://github.com/mxmzdlv/pybigquery
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SQLAlchemy dialect and API client for BigQuery.

extra:
  recipe-maintainers:
    - tim-werner
